# Generated by Django 3.2 on 2022-07-10 20:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection', models.BooleanField(default=False, verbose_name='Take Data Protection into account at all times')),
                ('encrypt', models.BooleanField(default=False, verbose_name='Encrypt, pseudonymize, or anonymize personal data whenever possible')),
                ('policy', models.BooleanField(default=False, verbose_name='Create an internal security policy for your team members, and build awareness about data protection')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
