# Generated by Django 3.2 on 2022-07-11 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protection', models.BooleanField(default=False, verbose_name='Take Data Protection into account at all times')),
                ('encrypt', models.BooleanField(default=False, verbose_name='Encrypt, pseudonymize, or anonymize personal data whenever possible')),
                ('policy', models.BooleanField(default=False, verbose_name='Create an internal security policy for your team members, and build awareness about data protection')),
            ],
        ),
        migrations.CreateModel(
            name='DpaChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('governance', multiselectfield.db.fields.MultiSelectField(choices=[('g1', 'Appoint a Data Protection Officer (if necessary)'), ('g2', 'Designate someone responsible for ensuring DPA compliance in your organization'), ('g3', 'Sign a data processing agreement between your organization and third parties')], max_length=8)),
                ('privacy', multiselectfield.db.fields.MultiSelectField(choices=[('pr1', 'It is easy for your customers to ask you to stop processing their data'), ('pr2', 'It is easy for your customers to request you t have their personal data deleted'), ('pr3', 'It is easy for your customers to correct or update inaccurate of incomplete information'), ('pr4', 'It is easy for your customers to request and receive all the information you have about them')], max_length=15)),
                ('security', multiselectfield.db.fields.MultiSelectField(choices=[('ds1', 'Have internal security policy for your team members, and build awareness on data protection'), ('ds2', 'Have a mechanism to notify authorities and data subjects in the event of a data breach'), ('ds3', 'Encrypt or anonymize personal data wherever possible')], max_length=11)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
