# Generated by Django 3.2 on 2022-07-14 20:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchecklist',
            name='date_filled',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checklist',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='checklist.category'),
        ),
    ]
