# Generated by Django 3.2 on 2022-07-12 09:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0002_dpachecklist_governance'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policies', models.BooleanField(default=False, verbose_name='Have internal security policy for your team members, and build awareness on data protection')),
                ('notification', models.BooleanField(default=False, verbose_name='Have a mechanism to notify authorities and data subjects in the event of a data breach')),
                ('encryption', models.BooleanField(default=False, verbose_name='Encrypt or anonymize personal data wherever possible')),
            ],
        ),
        migrations.CreateModel(
            name='PrivacyRights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_processing', models.BooleanField(default=False, verbose_name='It is easy for your customers to ask you to stop processing their data')),
                ('delete_data', models.BooleanField(default=False, verbose_name='It is easy for your customers to request you t have their personal data deleted')),
                ('update', models.BooleanField(default=False, verbose_name='It is easy for your customers to correct or update inaccurate of incomplete information')),
                ('request_info', models.BooleanField(default=False, verbose_name='It is easy for your customers to request and receive all the information you have about them')),
            ],
        ),
        migrations.RemoveField(
            model_name='governance',
            name='description',
        ),
        migrations.AddField(
            model_name='governance',
            name='agreement',
            field=models.BooleanField(default=False, verbose_name='Sign a data processing agreement between your organization and third parties'),
        ),
        migrations.AddField(
            model_name='governance',
            name='dpa_implementation',
            field=models.BooleanField(default=False, verbose_name='Designate someone responsible for ensuring DPA compliance in your organization'),
        ),
        migrations.AddField(
            model_name='governance',
            name='dpo',
            field=models.BooleanField(default=False, verbose_name='Appoint a Data Protection Officer (if necessary)'),
        ),
        migrations.AlterField(
            model_name='checklist',
            name='protection',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UsersChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_security', models.ManyToManyField(to='checklist.DataSecurity')),
                ('governance', models.ManyToManyField(to='checklist.Governance')),
                ('privacy', models.ManyToManyField(to='checklist.PrivacyRights')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
