# Generated by Django 3.2 on 2022-07-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0002_auto_20220714_2002'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklist',
            name='is_checked',
        ),
        migrations.AddField(
            model_name='checklist',
            name='implemented',
            field=models.BooleanField(default=False, verbose_name='Implemented'),
        ),
    ]
