# Generated by Django 3.2 on 2022-07-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0003_auto_20220712_0932'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=100)),
                ('checklist_item1', models.CharField(max_length=250)),
                ('checklist_item2', models.CharField(max_length=250)),
                ('checklist_item3', models.CharField(max_length=250)),
                ('checklist_item4', models.CharField(max_length=250)),
                ('checklist_item5', models.CharField(max_length=250)),
                ('score', models.CharField(max_length=250)),
            ],
        ),
    ]
