# Generated by Django 3.2 on 2022-07-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0005_policiesdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchecklist',
            name='is_checked',
            field=models.BooleanField(default=False),
        ),
    ]
