# Generated by Django 3.2 on 2022-07-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0007_auto_20220717_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='userchecklist',
            name='percentage_score',
            field=models.IntegerField(default=0),
        ),
    ]
