# Generated by Django 3.2 on 2022-07-18 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0008_userchecklist_percentage_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklist',
            name='brief_description',
            field=models.TextField(default='Required for DPA compliance', max_length=300),
        ),
    ]
