# Generated by Django 3.2 on 2022-07-21 09:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('checklist', '0010_alter_checklist_checklist_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserChecklistEntries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percent_s', models.PositiveIntegerField(default=0)),
                ('total_values', models.PositiveIntegerField(default=0)),
                ('user_score', models.PositiveIntegerField(default=0)),
                ('tier', models.CharField(default='Non-compliant', max_length=20)),
                ('date_filled', models.DateTimeField(auto_now_add=True)),
                ('checklist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='checklist.checklist')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Checklist Entries',
            },
        ),
    ]
