# Generated by Django 3.2 on 2022-07-25 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0011_userchecklistentries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policiesdocuments',
            name='document',
        ),
        migrations.AddField(
            model_name='policiesdocuments',
            name='data_processor_contracts',
            field=models.FileField(null=True, upload_to='policies/'),
        ),
        migrations.AddField(
            model_name='policiesdocuments',
            name='data_protection',
            field=models.FileField(null=True, upload_to='policies/'),
        ),
        migrations.AddField(
            model_name='policiesdocuments',
            name='data_retention',
            field=models.FileField(null=True, upload_to='policies/'),
        ),
        migrations.AddField(
            model_name='policiesdocuments',
            name='data_security',
            field=models.FileField(null=True, upload_to='policies/'),
        ),
        migrations.AddField(
            model_name='policiesdocuments',
            name='data_sharing_agreements',
            field=models.FileField(null=True, upload_to='policies/'),
        ),
        migrations.AddField(
            model_name='policiesdocuments',
            name='privacy',
            field=models.FileField(null=True, upload_to='policies/'),
        ),
        migrations.AddField(
            model_name='policiesdocuments',
            name='system_use_procedures',
            field=models.FileField(null=True, upload_to='policies/'),
        ),
    ]
