# Generated by Django 3.2 on 2022-07-25 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0012_auto_20220725_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesdocuments',
            name='data_processor_contracts',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='data_protection',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='data_retention',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='data_security',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='data_sharing_agreements',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='privacy',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='system_use_procedures',
            field=models.FileField(blank=True, null=True, upload_to='policies/'),
        ),
    ]
