# Generated by Django 3.2 on 2022-07-25 20:23

import checklist.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checklist', '0013_auto_20220725_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policiesdocuments',
            name='data_processor_contracts',
            field=models.FileField(blank=True, null=True, upload_to='policies/', validators=[checklist.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='data_protection',
            field=models.FileField(blank=True, null=True, upload_to='policies/', validators=[checklist.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='data_retention',
            field=models.FileField(blank=True, null=True, upload_to='policies/', validators=[checklist.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='data_security',
            field=models.FileField(blank=True, null=True, upload_to='policies/', validators=[checklist.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='data_sharing_agreements',
            field=models.FileField(blank=True, null=True, upload_to='policies/', validators=[checklist.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='privacy',
            field=models.FileField(blank=True, null=True, upload_to='policies/', validators=[checklist.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='policiesdocuments',
            name='system_use_procedures',
            field=models.FileField(blank=True, null=True, upload_to='policies/', validators=[checklist.models.validate_file_extension]),
        ),
    ]
