from django.urls import path

from .views import HomePageView, ChecklistPageView, DpaPageView, FaqPageView, ResultsPageView

# Article views
from . import views


app_name = 'checklist'
urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    # path('checklist/', ChecklistPageView.as_view(), name='checklist'),
    path('checklist/', views.checklist_view, name='checklist'),
    path('results/', ResultsPageView.as_view(), name='results'),
    path('faq/', FaqPageView.as_view(), name='faq'),
    path('dpa/', views.dpa_view, name='dpa'),
    path('regulations/', views.dpa_regulations_view, name='dpa_regulations'),
    path('icomply/', views.icomply_checklist_view, name='icomply'),
    path('checklist_submitted/', views.ChecklistSubmitView.as_view(), name='checklist_submitted'),



    # Articles
    path('dpa-section-1/', views.ArticleOneView.as_view(), name='art1'),
    path('dpa-section-2/', views.Article2View.as_view(), name='art2'),
    path('dpa-section-3/', views.Article3View.as_view(), name='art3'),
    path('dpa-section-4/', views.Article4View.as_view(), name='art4'),
    path('dpa-section-5/', views.Article5View.as_view(), name='art5'),
    path('dpa-section-6/', views.Article6View.as_view(), name='art6'),
    path('dpa-section-7/', views.Article7View.as_view(), name='art7'),
    path('dpa-section-8/', views.Article8View.as_view(), name='art8'),
    path('dpa-section-9/', views.Article9View.as_view(), name='art9'),
    path('dpa-section-10/', views.Article10View.as_view(), name='art10'),
    path('dpa-section-11/', views.Article11View.as_view(), name='art11'),
    path('dpa-section-12/', views.Article12View.as_view(), name='art12'),
    path('dpa-section-13/', views.Article13View.as_view(), name='art13'),
    path('dpa-section-14/', views.Article14View.as_view(), name='art14'),
    path('dpa-section-15/', views.Article15View.as_view(), name='art15'),
    path('dpa-section-16/', views.Article16View.as_view(), name='art16'),
    path('dpa-section-17/', views.Article17View.as_view(), name='art17'),
    path('dpa-section-18/', views.Article18View.as_view(), name='art18'),
    path('dpa-section-19/', views.Article19View.as_view(), name='art19'),
    path('dpa-section-20/', views.Article20View.as_view(), name='art20'),
    path('dpa-section-21/', views.Article21View.as_view(), name='art21'),
    path('dpa-section-22/', views.Article22View.as_view(), name='art22'),
    path('dpa-section-23/', views.Article23View.as_view(), name='art23'),
    path('dpa-section-24/', views.Article24View.as_view(), name='art24'),
    path('dpa-section-25/', views.Article25View.as_view(), name='art25'),
    path('dpa-section-26/', views.Article26View.as_view(), name='art26'),
    path('dpa-section-27/', views.Article27View.as_view(), name='art27'),
    path('dpa-section-28/', views.Article28View.as_view(), name='art28'),
    path('dpa-section-29/', views.Article29View.as_view(), name='art29'),
    path('dpa-section-30/', views.Article30View.as_view(), name='art30'),
    path('dpa-section-31/', views.Article31View.as_view(), name='art31'),
    path('dpa-section-32/', views.Article32View.as_view(), name='art32'),
    path('dpa-section-32/', views.Article33View.as_view(), name='art33'),
    path('dpa-section-33/', views.Article34View.as_view(), name='art34'),
    path('dpa-section-34/', views.Article35View.as_view(), name='art35'),
    path('dpa-section-35/', views.Article36View.as_view(), name='art36'),
    path('dpa-section-36/', views.Article37View.as_view(), name='art37'),
    path('dpa-section-37/', views.Article38View.as_view(), name='art38'),
    path('dpa-section-38/', views.Article39View.as_view(), name='art39'),
    path('dpa-section-39/', views.Article40View.as_view(), name='art40'),
    path('dpa-section-40/', views.Article41View.as_view(), name='art41'),
    path('dpa-section-41/', views.Article42View.as_view(), name='art42'),
    path('dpa-section-42/', views.Article43View.as_view(), name='art43'),
    path('dpa-section-43/', views.Article44View.as_view(), name='art44'),
    path('dpa-section-44/', views.Article45View.as_view(), name='art45'),
    path('dpa-section-45/', views.Article46View.as_view(), name='art46'),
    path('dpa-section-46/', views.Article47View.as_view(), name='art47'),
    path('dpa-section-47/', views.Article48View.as_view(), name='art48'),
    path('dpa-section-48/', views.Article49View.as_view(), name='art49'),
    path('dpa-section-49/', views.Article50View.as_view(), name='art50'),
    path('dpa-section-50/', views.Article51View.as_view(), name='art51'),
    path('dpa-section-51/', views.Article52View.as_view(), name='art52'),
    path('dpa-section-52/', views.Article53View.as_view(), name='art53'),
    path('dpa-section-53/', views.Article54View.as_view(), name='art54'),
    path('dpa-section-54/', views.Article55View.as_view(), name='art55'),
    path('dpa-section-55/', views.Article56View.as_view(), name='art56'),
    path('dpa-section-56/', views.Article57View.as_view(), name='art57'),
    path('dpa-section-57/', views.Article58View.as_view(), name='art58'),
    path('dpa-section-58/', views.Article59View.as_view(), name='art59'),
    path('dpa-section-59/', views.Article60View.as_view(), name='art60'),
    path('dpa-section-60/', views.Article61View.as_view(), name='art61'),
    path('dpa-section-61/', views.Article62View.as_view(), name='art62'),
    path('dpa-section-62/', views.Article63View.as_view(), name='art63'),
    path('dpa-section-63/', views.Article64View.as_view(), name='art64'),
    path('dpa-section-64/', views.Article65View.as_view(), name='art65'),
    path('dpa-section-65/', views.Article66View.as_view(), name='art66'),
    path('dpa-section-66/', views.Article67View.as_view(), name='art67'),
    path('dpa-section-67/', views.Article68View.as_view(), name='art68'),
    path('dpa-section-68/', views.Article69View.as_view(), name='art69'),
    path('dpa-section-69/', views.Article70View.as_view(), name='art70'),
    path('dpa-section-70/', views.Article71View.as_view(), name='art71'),
    path('dpa-section-71/', views.Article72View.as_view(), name='art72'),
    path('dpa-section-72/', views.Article73View.as_view(), name='art73'),
    path('dpa-section-73/', views.Article74View.as_view(), name='art74'),
    path('dpa-section-74/', views.Article75View.as_view(), name='art75'),
]
